version: '3'
services:
  scraper:
    build: .
    volumes:
      - .:/workspace
      - /workspace/node_modules
    links:
      - s3
    depends_on:
      - s3
    environment:
      - S3_ACCESS_KEY_ID=ACCESS_KEY_ID
      - S3_SECRET_ACCESS_KEY=SECRET_ACCESS_KEY
    env_file: .env
  s3:
    image: lphoward/fake-s3
    ports:
      - "${S3_EXTERNAL_PORT}:4569"